### ISSUE TITLE
Suppressing/disabling replies and re-tweets.

### ISSUE THREAD

**Issue by merson316** [NNTin/discord-twitter-bot#4]
Hello,

Are there any options to disable or suppress re-tweets and/or replies? We want to use this to stream https://twitter.com/PUBATTLEGROUNDS tweets for status updates but as you can see, they reply to everyone when they fix something which would cause **a lot** of spam.

Thanks for the work so far, it's visually one of the best twitter bots I've used so far.

**Comment by NNTin** [comment]
This has been suggested before and it can be done. I will get to it when I have time.
