### ISSUE TITLE
Tweets at the same time

### ISSUE THREAD

**Issue by designgears** [NNTin/discord-twitter-bot#8]
Tweets at the same time from the same account end up a little wonky when sent to discord. 

![image](https://user-images.githubusercontent.com/799451/31206400-cff7090e-a934-11e7-9274-207ab1c26bb8.png)

**Comment by NNTin** [comment]
That's intended. He was referencing another tweet. This is why you see 2 tweets. [image](https://user-images.githubusercontent.com/18033169/31216509-33b47b3c-a9b4-11e7-9ce4-dea55a7737b2.png)  
The 2 tweets weren't sent at the same time and it would have still worked if he was referencing someone else.
